### PR TITLE
IOS button fix

### LINKED ISSUE #124: Pagination dots are ellipses instead of circles on iPhone device
**Describe the bug**
Carousel pagination dots are ellipses instead of circles on iPhone devices.

**To Reproduce**
My colleague checked this on his iPhone 12 Max and I see the same on the iPhone emulator in Xcode. This problem exists even on official examples: https://sag1v.github.io/react-elastic-carousel/

**Expected behavior**
Dots should be always circles, not ellipses.

**Sandbox link**
Sandbox link is not needed, because this problem exists even on official examples. Just take the iPhone or use the Xcode iPhone simulator to check this.

**Screenshots**
Carousel Style Problem

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max
 - OS: iOS 14.2
 - Browser: Safari
 - Version: Latest

### PR DESCRIPTION
**Pull request by sag1v**
remove padding for buttons resolve #124

### CODE REVIEW

File: src/react-elastic-carousel/components/styled/Button.js [hunk 1]
```diff
@@ -1,13 +1,15 @@
 import styled from "styled-components";
 
 export default styled.button.attrs(({ type = "button" }) => ({ type }))`
+  box-sizing: border-box;
```
Comment (tomaszzmudzinski) [inline src/react-elastic-carousel/components/styled/Button.js:4]: I believe that this line is not needed to fix issue on iOS. Setting padding to 0 is enough 👍

Comment (sag1v) [reply src/react-elastic-carousel/components/styled/Button.js:4]: yeah, most browser defaults to that but AFAIK some UI lib has a general rule that might override it.
