### PR TITLE
Fixed the arrow and dot buttons as they were submitting the form

### LINKED ISSUE #63: Clicking the arrow buttons will submit a form.
**Describe the bug**
The arrow buttons are submitting a form as they have no type specified.

**  Fix **
Just add `type={"button"}` in src/react-elastic-carousel/components/Arrow.js

This is an easy fix. Just need to add one line of code in Arrow.

### PR DESCRIPTION
**Pull request by superjose**
Fixes #63

### CODE REVIEW

**Comment by superjose** [comment]
@sag1v BTW, how do you want me to do the typings? Do you want me to base it off this branch or do you want me to wait for you to merge it, so I can rebase it and then push the changes?

File: src/react-elastic-carousel/components/Pagination/Dot.js [hunk 1]
```diff
@@ -37,6 +37,7 @@ class DotContainer extends React.Component {
     const { active } = this.props;
     return (
       <Dot
+        type="button"
```
Comment (sag1v) [inline src/react-elastic-carousel/components/Pagination/Dot.js:40]: I would do it in the `Dot` component itself (line 10) in case we use `Dot` in other places:

```jsx
const Dot = styled.button.attrs(() => ({ type: "button" }))`
  transition: all 250ms ease;
  border: none;
  margin: 5px;
  // ...
`
```

File: src/react-elastic-carousel/components/Arrow.js [hunk 2]
```diff
@@ -28,6 +28,7 @@ const Arrow = ({ direction, onClick, icons, style, ...rest }) => {
   };
   return (
     <Button
+      type="button"
```
Comment (sag1v) [inline src/react-elastic-carousel/components/Arrow.js:31]: I would add that attribute in `Button` itself in case we will use it in other places:

```jsx
export default styled.button.attrs(({ type = "button" }) => ({ type }))`
  transition: all 0.3s ease;
  font-size: 1.6em;
  background-color: rgba(103, 58, 183, 0.1);
  // ...
`
```

**Comment by sag1v** [comment]
@superjose  Thank you! 🙏

**Comment by superjose** [comment]
Awesome 😁. Let me do it now for the typings.

**Comment by sag1v** [comment]
> Awesome 😁. Let me do it now for the typings.

Great! Don't forget to pull master
